implemented addCollaborator and removeCollaborator to Repository
nmoya/github pull request #1
Opened 2016-11-11 23:08 UTC by marwan-at-work

2016-11-11 23:32 UTC, nmoya commented on lib/Repository.js
> -   updateStatus(commitSHA, options, cb) {
Why remove this function?

2016-11-11 23:32 UTC, nmoya commented on lib/Repository.js
> -   updateRepository(options, cb) {
And this?

2016-11-11 23:32 UTC, nmoya commented on lib/Repository.js
> +      log('Deprecated: This method contains a typo and it has been deprecated. It will be removed in next major version. Use updatePullRequest() instead.'); // eslint-disable-line
revert this?

2016-11-11 23:33 UTC, nmoya requested changes
The 4th commit is deleting the functions that were implemented in commits 1 and 3.

2016-11-11 23:37 UTC, marwan-at-work commented on lib/Repository.js
> -   updateStatus(commitSHA, options, cb) {
@nmoya i think this happened when rebasing cuz i worked on it on `master` then moved it to the other branch. i'll fix and resubmit. thanks!

2016-11-11 23:51 UTC, marwan-at-work commented
@nmoya fixed

2016-11-11 23:52 UTC, nmoya commented on lib/Repository.js
> +    * @param {Requestable.callback} [cb] - will receive the list of PRs
List of PRs? isn't the repositories, the invitee and the inviter?

2016-11-11 23:53 UTC, nmoya commented on lib/Repository.js
> +    * @param {Requestable.callback} [cb] - will receive the list of PRs
same

2016-11-11 23:54 UTC, nmoya commented on lib/Repository.js
> +    * @param {Object} options - options with username as collaborator - permission (optional)
Can you specify the keys inside the options object like this:

```
    * @param {string} [options.target_url] - The target URL to associate with this status.
    * @param {string} [options.description] - A short description of the status.
    * @param {string} [options.context] - A string label to differentiate this status among CI systems.
```

2016-11-11 23:56 UTC, nmoya commented
Other than minors on comments, LGTM.

2016-11-11 23:56 UTC, nmoya approved these changes

2016-11-12 00:00 UTC, marwan-at-work commented on lib/Repository.js
> +    * @param {Requestable.callback} [cb] - will receive the list of PRs
@nmoya every single method has this param in the Repository class. They get past to the `_request` method. So I'm not sure what the reason is.

2016-11-12 00:11 UTC, merged